files:
  - source: /*.md
    translation: /%locale%/%original_file_name%
    languages_mapping:
      locale:
        de: Deutsch
        fr: Kukuku
  - source: /res/values/strings.xml
    translation: /test/hello/%locale%/%original_file_name%
